[project]
name = "agent-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "addict>=2.4.0",
    "datasets>=4.4.2",
    "modelscope>=1.33.0",
    "numpy>=2.4.0",
]
